name: Release – Publish

on:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get current version
        id: version-file
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT

      - name: Resolve Packages
        run: swift package resolve --verbose

      - name: Install xcbeautify
        run: |
          brew list xcbeautify || brew install xcbeautify

      - name: Run unit tests
        uses: ./.github/composite_actions/run_xcodebuild_tests
        timeout-minutes: 15
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

      - uses: ffurrer2/extract-release-notes@273da39a24fb7db106a35526c8162815faffd31d # v3.1.0
        id: extract-release-notes
        with:
          changelog_file: CHANGELOG.md

      - name: Changelog
        run: echo "${{ steps.extract-release-notes.outputs.release_notes }}"

      - name: Create Github release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          makeLatest: true
          tag: ${{ steps.version-file.outputs.release-version }}
          body: |
            ## Release notes:
            ${{ steps.extract-release-notes.outputs.release_notes }}

  publish-cocoapods:
    needs: build-and-release
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push RoktUXHelper.podspec --allow-warnings
