coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
  ignore:
    - Example/Tests
    - Tests/Rokt_WidgetTests
    - Tests/SizeReport
