env:
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium

steps:
  - label: ":broom: Code Quality Scan with trunk"
    key: "trunk"
    agents:
      queue: ${MAC_BK_AGENT}
    plugins:
      - ssh://git@github.com/ROKT/trunk-buildkite-plugin.git#stable:
          team: Mobile-Integrations
          check_args: --ci --all
    soft_fail: true
