env:
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium
  ENG_BK_AGENT: eng-default

steps:
  - label: ":broom: Code Quality Scan with trunk"
    key: "trunk"
    agents:
      queue: ${ENG_BK_AGENT}
    plugins:
      - ssh://git@github.com/ROKT/trunk-buildkite-plugin.git#stable:
          team: Mobile-Integrations
          check_args: --ci --all
    soft_fail: true

  - label: ":swift: Update Swift Package"
    commands:
      - . ~/.zshrc
      - rbenv local 3.2.2
      - ./.buildkite/bin/update_version.sh "${VERSION}" Package.swift README.md
      - ./.buildkite/bin/create_tag_and_update_branch.sh "${VERSION}" "${SPM_UPDATE}"
    agents:
      queue: ${MAC_BK_AGENT}
