env:
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium

steps:
  - label: ":swift: Update Swift Package"
    commands:
      - . ~/.zshrc
      - rbenv local 2.7.6
      - ./.buildkite/bin/update_version.sh "${VERSION}" Package.swift README.md
      - ./.buildkite/bin/create_tag_and_update_branch.sh "${VERSION}" "${SPM_UPDATE}"
    agents:
      queue: ${MAC_BK_AGENT}